---

- name: Restart carbon-cache
  service: name=carbon-cache state=restarted
  
- name: Reload apache
  service: "name={{ apache_service }} state=reloaded"

- name: Restart apache
  service: "name={{ apache_service }} state=restarted"